# Generated by Django 5.0.6 on 2024-07-12 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitros',
            fields=[
                ('cedula', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombreCompleto', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('disciplina', models.CharField(blank=True, max_length=50, null=True)),
                ('tipoArbitro', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(max_length=10)),
                ('localidad', models.CharField(blank=True, max_length=50, null=True)),
                ('perfilDeportivo', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('cedula_Organizador', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_inicio', models.DateField()),
                ('fecha_de_finalizacion', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField()),
                ('localidad', models.CharField(choices=[('Usaquén', 'Usaquén'), ('Chapinero', 'Chapinero'), ('Santa Fe', 'Santa Fe'), ('San Cristóbal', 'San Cristóbal'), ('Usme', 'Usme'), ('Tunjuelito', 'Tunjuelito'), ('Bosa', 'Bosa'), ('Kennedy', 'Kennedy'), ('Fontibón', 'Fontibón'), ('Engativá', 'Engativá'), ('Suba', 'Suba'), ('Barrios Unidos', 'Barrios Unidos'), ('Teusaquillo', 'Teusaquillo'), ('Los Mártires', 'Los Mártires'), ('Antonio Nariño', 'Antonio Nariño'), ('Puente Aranda', 'Puente Aranda'), ('La Candelaria', 'La Candelaria'), ('Rafael Uribe Uribe', 'Rafael Uribe Uribe'), ('Ciudad Bolívar', 'Ciudad Bolívar'), ('Usme', 'Usme'), ('Tunjuelito', 'Tunjuelito'), ('Bosa', 'Bosa'), ('Kennedy', 'Kennedy'), ('Fontibón', 'Fontibón'), ('Engativá', 'Engativá'), ('Suba', 'Suba'), ('Barrios Unidos', 'Barrios Unidos'), ('Teusaquillo', 'Teusaquillo'), ('Los Mártires', 'Los Mártires'), ('Antonio Nariño', 'Antonio Nariño'), ('Puente Aranda', 'Puente Aranda'), ('La Candelaria', 'La Candelaria'), ('Rafael Uribe Uribe', 'Rafael Uribe Uribe'), ('Ciudad Bolívar', 'Ciudad Bolívar'), ('Sumapaz', 'Sumapaz'), ('Soacha', 'Soacha')], max_length=20)),
                ('lugar', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('amistoso', 'Amistoso'), ('torneo', 'Torneo')], max_length=20)),
                ('tipo_de_arbitro', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('espera', 'Espera'), ('reservado', 'Reservado'), ('compleatdo', 'Compleatdo')], max_length=20)),
                ('arbitros', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mi_app.arbitros')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.organizador')),
            ],
        ),
    ]
